### ISSUE TITLE
./server.py

### ISSUE THREAD

**Issue by dmolina213** [MISP/misp-dashboard#119]
when i try to run ./server.py i get this message. not sure if it is just a warning or an outright error. Any ideas what is happenning? are there components missing? how do i fix this ?
Traceback (most recent call last):
  File "./server.py", line 54, in <module>
    geo_helper = geo_helper.Geo_helper(serv_redis_db, cfg)
  File "/usr/local/src/MISP_dashboard2/misp-dashboard/helpers/geo_helper.py", line 65, in __init__
    self.country_to_iso = { country.name: country.alpha_2 for country in pycountry.countries}
  File "/usr/local/src/MISP_dashboard2/misp-dashboard/helpers/geo_helper.py", line 65, in <dictcomp>
    self.country_to_iso = { country.name: country.alpha_2 for country in pycountry.countries}
AttributeError: 'Country' object has no attribute 'alpha_2'

**Comment by mokaddem** [comment]
Should be fixed with #121.
Please re-open if it's not the case.
