### ISSUE TITLE
Exceptions TooManyRedirects

### ISSUE THREAD

**Issue by f00bar10** [MISP/misp-dashboard#134]
Hi guys,

I have installed MISP using the latest script available (https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh) using -A option for installing everything.

The problem is when I try to access to misp dashboard because I get the error "ERR_TOO_MANY_REDIRECTS" in web browsers.

When I run the diagnostic.py script, I get the following output:

> ✔ Virtual environment and packages
✔ Configuration
✔ File permission
✔ Redis
✔ Zmq
✔ Processes status: Both processes are running
✔ Subscriber status: subscriber is running and populating the buffer
ℹ Buffer queue: Currently 1 items in the buffer
✔ Buffer change rate: Buffer is consumed faster than being populated
✔ Dispatcher status: Took 0.69s to complete
Traceback (most recent call last):
  File "diagnostic.py", line 447, in <module>
    main()
  File "diagnostic.py", line 443, in main
    start_diagnostic()
  File "diagnostic.py", line 438, in start_diagnostic
    if check_server_listening() and dispatcher_running:
  File "diagnostic.py", line 70, in wrapper_add_spinner
    result = func(spinner, *args, **kwargs)
  File "diagnostic.py", line 379, in check_server_listening
    r = requests.get(url)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

Do you have any idea?

Thanks in advance!!

Regards! :D

**Comment by mokaddem** [comment]
Hey!
I improved a bit the diagnostic and feedback if anything went wrong in #135.
I hope it helps fixing your issue.
Cheers!

**Comment by f00bar10** [comment]
Thanks for the answer!!

I have tried the new script but I am getting the same same error again...

`(DASHENV) misp@misp:/var/www/misp-dashboard$ python3 diagnostic-new.py
✔ Virtual environment and packages
✔ Configuration
✔ File permission
✔ Redis
✔ Zmq
✔ Processes status: Both processes are running
✔ Subscriber status: subscriber is running and populating the buffer
ℹ Buffer queue: Currently 1 items in the buffer
✔ Buffer change rate: Buffer is consumed faster than being populated
✔ Dispatcher status: Took 0.80s to complete
Traceback (most recent call last):
  File "diagnostic-new.py", line 492, in <module>
    main()
  File "diagnostic-new.py", line 488, in main
    start_diagnostic()
  File "diagnostic-new.py", line 483, in start_diagnostic
    if check_server_listening() and dispatcher_running:
  File "diagnostic-new.py", line 72, in wrapper_add_spinner
    result = func(spinner, *args, **kwargs)
  File "diagnostic-new.py", line 381, in check_server_listening
    r = requests.get(url)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/www/misp-dashboard/DASHENV/lib/python3.6/site-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
`

May you know why?

Thanks in advance!

**Comment by mokaddem** [comment]
Could you please have a look at this issue https://github.com/MISP/misp-dashboard/issues/137 and try to use the fix provided? Thanks

**Comment by f00bar10** [comment]
Thanks for the answer.

Yeah, It has worked by specifying to still save cookies on unsecured connections in _config.cfg_ setting _session_cookie_secure_ to false (it is for internal testing and I do not have SSL activated).

Really thanks!
Regards!

PD: the issue can be closed.
