### ISSUE TITLE
Error spotted once

### ISSUE THREAD

**Issue by mokaddem** [MISP/misp-dashboard#14]
```
[2017-12-04 10:28:59,005] ERROR in app: Exception on /_getOrgRank [GET]
Traceback (most recent call last):
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/git/MISP-Dashboard/DASHENV/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./server.py", line 387, in getOrgRank
    return jsonify(contributor_helper.getCurrentOrgRankFromRedis(org))
  File "/home/user/git/MISP-Dashboard/contributor_helper.py", line 523, in getCurrentOrgRankFromRedis
    remainingPts = self.getRemainingPoints(points)
  File "/home/user/git/MISP-Dashboard/contributor_helper.py", line 548, in getRemainingPoints
    for i in [math.floor(self.rankMultiplier**x) for x in range(1,self.levelMax+1)]:
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by adulau** [comment]
Cannot reproduce.
