### ISSUE TITLE
Returned non-zore exit status 1 when run diagnostic.py script

### ISSUE THREAD

**Issue by hmnguyen1201** [MISP/misp-dashboard#142]
Hi team,

Can you someone help me resolve this issue? I am trying to set up MISP dashboard for my MISP instance and having no luck so I tried the diagnostic.py to see where the problem is but the script fails as well.

`./diagnostic.py
✔ Virtual environment and packages
✔ Configuration
✔ File permission
✔ Redis
✔ Zmq
Traceback (most recent call last):
  File "./diagnostic.py", line 439, in <module>
    main()
  File "./diagnostic.py", line 435, in main
    start_diagnostic()
  File "./diagnostic.py", line 425, in start_diagnostic
    check_processes_status()
  File "./diagnostic.py", line 70, in wrapper_add_spinner
    result = func(spinner, *args, **kwargs)
  File "./diagnostic.py", line 218, in check_processes_status
    universal_newlines=True
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pgrep', '-laf', 'zmq_']' returned non-zero exit status 1.`

**Comment by mokaddem** [comment]
Hey, thanks for the feedback. I added a catch that should tell more about the error you are experiencing.
My guess is that you are trying to access process information (using `pgrep`) from a user that do not have the permission. Could it be?

**Comment by SteveClement** [comment]
@hmnguyen1201 any news on this issue?
