### ISSUE TITLE
An Error on request:

### ISSUE THREAD

**Issue by jessie4736** [MISP/misp-dashboard#2]
hello, happen to see a error from server.py:

127.0.0.1 - - [06/Nov/2017 05:24:52] "GET /_logs HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/werkzeug/serving.py", line 199, in execute
    for data in application_iter:
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/werkzeug/wsgi.py", line 704, in __next__
    return self._next()
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/home/jessie/misp/misp-dashboard/server.py", line 218, in event_stream_log
    for msg in subscriber_log.listen():
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 2501, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 2430, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 2408, in _execute
    return command(*args)
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/home/jessie/misp/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
AttributeError: 'NoneType' object has no attribute 'readline'

Kind regards
Jessie Lee

**Comment by mokaddem** [comment]
Hi,
Thanks for the report.
Does this error appear by itself? Also, does it prevents you from using the application?

**Comment by mokaddem** [comment]
Hi,
Is this still happening since the recent changes?

**Comment by adulau** [comment]
I will close the issue. If the issue still exists with the recent version, feel free to reopen the issue. Thank you very much.
