### ISSUE TITLE
float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by SHSauler** [MISP/misp-dashboard#21]
This happened when getting a feed. It worked for 10+ minutes, then hung on the following. Kinda hard to reconstruct. Sounds like an attribute with empty value? How would you troubleshoot this?

```python3
can't resolve ip
sending keepalive
Traceback (most recent call last):
  File "zmq_dispatcher.py", line 270, in <module>
    main(args.sleeptime)
  File "zmq_dispatcher.py", line 246, in main
    process_log(zmqName, content)
  File "zmq_dispatcher.py", line 228, in process_log
    dico_action[topic](zmq_name, jsonevent)
  File "zmq_dispatcher.py", line 76, in handler_dispatcher
    handler_event(zmq_name, jsonObj)
  File "zmq_dispatcher.py", line 157, in handler_event
    handler_attribute(zmq_name, jsoncopy)
  File "zmq_dispatcher.py", line 202, in handler_attribute
    geo_helper.getCoordFromIpAndPublish(jsonattr['value'], jsonattr['category'])
  File "/var/www/misp-dashboard/geo_helper.py", line 82, in getCoordFromIpAndPublish
    rep = self.ip_to_coord(supposed_ip)
  File "/var/www/misp-dashboard/geo_helper.py", line 162, in ip_to_coord
    lat = float(resp.location.latitude)
TypeError: float() argument must be a string or a number, not 'NoneType'
````

**Comment by mokaddem** [comment]
Thanks for the report,
It seems that sometimes, ``geoip2.database.Reader(self.PATH_TO_DB)`` does not return a location. We just need to check if the response from the reader have a ``location`` field.

**Comment by mokaddem** [comment]
Hi, 
This should be fixed now. (#25)

**Comment by SHSauler** [comment]
Will test, thanks a bunch
