### ISSUE TITLE
No option 'streamlogcachekey' in section: 'RedisLog'

### ISSUE THREAD

**Issue by faustus25** [MISP/misp-dashboard#69]
Updated to latest version today:

git describe --tags
v1.1-2-gce26610

Issue once I launch the startup scripts:

````
./start_all.sh
dashboard virtualenv seems to exist, good
tcp        0      0 0.0.0.0:6250            0.0.0.0:*               LISTEN
root      1615  0.4  0.1 213960 60420 ?        Sl    /usr/local/src/misp-dashboard/DASHENV/bin/python ./zmq_subscriber.py
        * NOT starting Redis server, made a very unrealiable check on port 6250, and something seems to be thereâ¦ please double check if this is good!
        * NOT starting zmq subscriber, made a rather unrealiable ps -auxw | grep for zmq_subscriber.py, and something seems to be thereâ¦ please double check if this is good!
        * Launching zmq dispatcher
        * Launching flask server
user@server:/usr/local/src/misp-dashboard# Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/local/src/misp-dashboard/DASHENV/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/src/misp-dashboard/DASHENV/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'maxcachehistory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zmq_dispatcher.py", line 49, in <module>
    live_helper = live_helper.Live_helper(serv_redis_db, cfg)
  File "/usr/local/src/misp-dashboard/helpers/live_helper.py", line 12, in __init__
    self.maxCacheHistory = cfg.get('Dashboard', 'maxCacheHistory')
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'maxcachehistory' in section: 'Dashboard'
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/local/src/misp-dashboard/DASHENV/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/src/misp-dashboard/DASHENV/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'streamlogcachekey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./server.py", line 45, in <module>
    streamLogCacheKey = cfg.get('RedisLog', 'streamLogCacheKey')
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'streamlogcachekey' in section: 'RedisLog'
````

**Comment by mokaddem** [comment]
Hi,
With the new update,  new fields in the configuration file have appeared.
You need to add these fields present in ``config/config.cfg.default`` to your ``config/config.cfg`` file.

**Comment by faustus25** [comment]
You are correct @mokaddem , the config file was preserved when I updated and did not contain the new values, following an edit to the config file and restart the dashboard is back.
